### ISSUE TITLE
Implement federation query planner to be used by Apollo Gateway

### ISSUE THREAD

**Issue by Enrico2** [apollographql/rust#101]
The first experiment for a Rust based Apollo gateway is to take an expensive operation that's currently happening in the Apollo Gateway, and implement it in rust, and use it from the Apollo Gateway via Wasm.

We chose the `buildQueryPlan` function because:
1. It's self contained, in that it's pretty much stateless, take in a schema and a query, and output a query plan.
1. It's simple enough for a first rust attempt, and complex enough to be expensive on the JS side.

Experimenting with `wasm_bindgen`, we've learned that we can serialize a `QueryPlan` to a `JsValue` to pass back into JS. Using the attribute directly on `QueryPlan` didn't work due to it supporting only C-style enums.

For now we're going to try that, bench and tune if we're not happy with the performance.

**Comment by Enrico2** [comment]
The prototype for bridging wasm and JS was done on this branch: https://github.com/apollographql/rust/tree/ran/wasm_bridge/wasm-bridge

**Comment by abernix** [comment]
@Enrico2 Thanks for opening this issue; exciting to have the prototype bridge done.

I realize the function is currently a hard-coded, but otherwise empty shell of a complete implementation, but if @JakeDawkins were to start implementing the query plan tests against a function, would it be an appropriate to do it on the `query_plan` function in this branch?

https://github.com/apollographql/rust/blob/f88556cc2e3535162e8f495083b8fb3ef2a55c02/wasm-bridge/src/lib.rs#L11-L13

(All the tests would fail unless they are the actual hard-coded query-plan that is currently in there.)

**Comment by Enrico2** [comment]
@abernix @JakeDawkins for testing purposes, it may make more sense to use a function like
```rust
type Result<T> = std::result::Result<T, QueryPlanError>;

// only used by tests for now
fn build_query_plan_from_str(schema: &str, query: &str) -> QueryPlan {
  let schema = parse_schema(schema).expect("failed parsing schema");
  let query = parse_query(query).expect("failed parsing query");
  build_query_plan(&schema, &query).expect("failed building QueryPlan")
}

fn build_query_plan(schema: &schema::Document, query: &query::Document) -> Result<QueryPlan> { .. }

```

I'm currently implementing the latter as a first step, but the API that will be used through wasm might be slightly different. The reason is that I think we're going to want to parse the schema once in Rust, and save it to an object, something that looks like

```rust

struct QueryPlanner {
  schema: schema::Document
}

impl QueryPlanner {
  // parses the schema
  pub fn new(schema: &str) -> Result<QueryPlanner> { .. }

  // parse the query, build a plan using `self.schema`
  pub fn get_query_plan(&self, query: query::Document) -> Result<QueryPlan> { 
    build_query_plan(self.schema, &query)
  }
}

```

If we write tests against the first suggestion here, moving it to use the "real" api will be trivial once it exists, I'm not yet sure how it's going to look like, this is just a first sketch.

**Comment by abernix** [comment]
@Enrico2 Sounds great to me; I like that suggestion.
