### ISSUE TITLE
Remove `cdn` and `cli` from the repo 

### ISSUE THREAD

**Issue by Enrico2** [apollographql/rust#116]
## Move the CLI to `apollo-cli`
The CLI is moving to https://github.com/apollographql/apollo-cli/
This work is in progress and will be done by @ashleygwilliams 

## Move the CDN to its own repository.
This involves moving the `cdn` code and related Github actions.

This will be done by @jbaxleyiii 

There's a tag in this repository for all of the code slated to be moved prior to it being removed, in https://github.com/apollographql/rust/tree/pre-cli-removal

## Delete the code from `Rust`
@Enrico2 will remove the code and update the relevant Github actions.

**Comment by ashleygwilliams** [comment]
cdn is used for the iOS installer, so should remain in this repo or be made into a separate repo IMO.
