### ISSUE TITLE
Directives for SDL representation of composed schema

### ISSUE THREAD

**Issue by abernix** [apollographql/rust#61]
Currently, in the JavaScript implementation of federation, we attach a number of attributes to the executable schema.  Within JavaScript query planning, we then use those attributes to determine the service which is responsible for fulfilling those types.

As the query planning logic is migrated to Rust — but also just as a more portable representation of a composed, executable schema — we should determine a set of directives that can decorate fields in a schema with the service that implements them.  Perhaps it's merely an annotation with `@service(name: 'products')`?

This may very well be discussed within the context of this issue for now, and eventually PR'd to the specification itself.

**Comment by trevor-scheer** [comment]
After conversations with both @queerviolet and @jbaxleyiii, we've landed on the following spec. This is still open for discussion and feedback is welcome!

```graphql
# Declares a graph's name and url on the schema definition.
# Each graph should have its own directive.
directive @graph(name: String!, url: String!) on SCHEMA

# Declares the owning graph of a type.
# In the special case of value types, multiple `owner` directives should exist.
directive @owner(graph: String!) on OBJECT

# Used to identify 2 things:
# 1) If the `graph` argument matches the `graph` argument on the `owner` directive
#    for this type, the `fields` argument defines one of the valid keys.
# 2) If the `graph` argument is different, this entity is being extended by the
#    named `graph` using the specified key, `fields`. The `fields` argument must
#    match one of the type owner's defined key `fields` (see #1).
directive @key(fields: _FieldSet!, graph: String!) on OBJECT

# The `resolve` directive identifies fields which extend an entity. The `graph`
# argument identifies which graph is used to resolve the field.
# In the special case of root types (`Query`, `Mutation`, `Subscription`), all
# fields must be annotated with `resolve` since the type is owned by the
# gateway itself.
directive @resolve(graph: String!) on FIELD_DEFINITION

# The resolution of this field also includes the resolution of the specified
# `fields` which are owned by another graph. This unlocks optimization for
# the gateway to resolve additional fields if and when it needs to without
# reaching to the graph where the specified fields are owned.
directive @provides(fields: _FieldSet!) on FIELD_DEFINITION

# A `requires` specifies a dependency on the `fields`. In order for this
# field to resolve, the gateway must first resolve the `fields` on the
# parent type.
directive @requires(fields: _FieldSet!) on FIELD_DEFINITION
```

**Comment by trevor-scheer** [comment]
An example result of composition:
```graphql
schema
  @graph(name: "products", url: "https://products.api.com/")
  @graph(name: "reviews", url: "https://reviews.api.com/")
  @graph(name: "authors", url: "https://authors.api.com/")
  @graph(name: "computed", url: "https://computed.api.com/")
{
  query: Query
}
# All root level fields must be annotated with the service that they belong to.
# root types are "owned" by the gateway i.e. they don't have an owning graph, and
# they can only be resolved by the gateway itself, not be any arbitray graph. Because of
# that, each field on the root types, needs to contain possible graphs that can provide
# the data requested. In the 1.0 where we only support a single "resolve", this is only one graph
type Query {
  products: [Product!] @resolve(graph: "products")
  author(id: String!): Author @resolve(graph: "authors")
}

# Which keys are defined, which fields are extended by which service, and which keys those extend fields use,
# and who the owning service is
type Product
  @owner(graph: "products")
  @key(fields: "upc", graph: "products")
  @key(fields: "sku { value }", graph: "products")
  @key(fields: "sku { value }", graph: "reviews")
{
  # Fields with no @resolve implicitly belong to the graph which owns the parent type.
  # In this case, the `products` graph.
  upc: String!
  sku: Sku!
  metadata: Metadata
  # Fields with an @resolve reflect that the parent type has been extended with this field
  # by the graph listed in the `graph` argument. The `keys` argument here must be
  # a list of length 1. The key must exist in the `keys` list on the parent type.
  reviews: [Review!] @resolve(graph: "reviews")
}

# No `keys`, so this type is not an entity. Since this is not an entity,
# all fields of type `Sku` must be owned by the `products` graph. The
# resolve annotation on this type would unlock that validation
type Sku {
  value: String!
}

type Review
  @owner(graph: "reviews")
  @key(fields: "id", graph: "reviews")
  @key(fields: "id", graph: "computed")
{
  id: String!
  content: String!
  metadata: Metadata
  # The `computed` graph adds the `length` field to the `Review` type.
  # `requires` should look and act in a familiar way here.
  # We could validate that the fieldset only points to fields on the owning graph.
  length: Int! @resolve(graph: "computed") @requires(fields: "content")
}

type Author {
  id: String!
  name: String!
  metadata: Metadata
  # Here, the `authors` graph is also able to resolve the content on a `Review`,
  # as noted by the `@provides`
  reviews: [Review!] @provides(fields: "content")
}

# Value type example with multiple owners
type Metadata
  @owner(graph: "author")
  @owner(graph: "products")
  @owner(graph: "reviews")
{
  key: String
  value: String
}
```

**Comment by abernix** [comment]
@trevor-scheer This is super well presented.  Thank you!

The existence of `schema { ... }` notation really surprised me, though I suppose I should have expected it to be possible for there to be a `SchemaDefinition` within SDL: _**S**chema_ **D**efinition **L**anguage.  Cool!

✅ This LGTM.

What do you imagine the steps toward implementing this look like?

**Comment by abernix** [comment]
Follow-up question: What is the reason for including `url` in the `@graph` directive parameters?

**Comment by jbaxleyiii** [comment]
@abernix the `@graph` directive lets us build up a static representation of the current `serviceList` functionality

**Comment by glasser** [comment]
This is a lovely spec!  A few questions:

># Declares a graph's name and url on the schema definition.

(a) Is this `name` something that is expected to be meaningful outside of the schema (eg, related to names for graphs in the Apollo registry), or is it purely intended to be a target of the other directives, for error messages and the like when executing the graph, etc?

(b) Should we specify that "url" is specifically the URL at which you can execute GraphQL (not, like, an informational page on the registry or whatever)?

(c) Do we want to have some field for identifying that a graph in `@graph` exists in the registry under a given name, or should we're a bit farther down that path to think about that?

(d) Do we need to do any sort of versioning on the overall composed-graph format?  ie should this declare something like `@composedGraph(version: 1)` so that consumers of this composed graph (eg gateways) can be confident that they actually understand the file they're receiving from composition?

**Comment by trevor-scheer** [comment]
I lost a nice draft I had to this...retyping.

@glasser thanks for taking a look and providing input. Please let me know if you have any further questions :)

a) The `name` here === `serviceName`, so yes it does have significance as an identifier outside of the scope of the document itself.

b) I personally think `url` is sufficient, but I'm curious to hear your thoughts. If it's too vague or you think there may be other relevant urls, then I would be happy changing to something like `endpoint` or `endpointUrl`.

c) Can you elaborate? I don't quite understand what 'field' you might be referring to? Is that an argument to the `@graph` directive? i.e.
`@graph(url: "...", isRegistered: true)`

d) I think this is a great suggestion and I'll add it. As a bonus, we can add other composed graph metadata to this directive in the future if we find other useful annotations.

**Comment by glasser** [comment]
b) I think the token `url` is fine but perhaps the comment could be more explicit?

c) Yeah, I meant an argument to `@graph` (or a different directive). Specifying a name probably, not just a boolean. I think this is more of a "let's make sure this meshes with plans for graphs-composing-graphs coming from Gravity" (cc @zionts) and probably not any change needed right now?

**Comment by trevor-scheer** [comment]
Oops, my c) example is missing the `name` in my most recent comment. Which I think you've noted by saying no change needed right now.

**Comment by glasser** [comment]
Well I mean it would reference a Studio graph ID, which might not be the same as a `name`?

**Comment by abernix** [comment]
I'm having a small amount of buyer's remorse around `@owner` from a naming standpoint.  In some sense, we're trying to move away from "type ownership", but this seems to solidify it (in terms of naming).

**Comment by jbaxleyiii** [comment]
@abernix our thought was when we are ready to remove the restriction of single type ownership, we remove that annotation all together

**Comment by trevor-scheer** [comment]
Closed by https://github.com/apollographql/apollo-server/pull/4405
