### ISSUE TITLE
Figure out Rust <-> Gateway bridge package repository

### ISSUE THREAD

**Issue by Enrico2** [apollographql/rust#68]
Very soon, we are planning on invoking code written in Rust from code written in Typescript from Apollo Gateway.

So far we've agreed on the following set up:
1. A pure Rust package containing the Rust objects, business logic, etc.
1. A wasm bridge rust+js, this one depends on the pure Rust packages and exposes js/ts (not sure yet) to be used by the gateway. 
1. The gateway ts code will have a dependency on the bridge package and will use whatever it exposes.

There is a question of where should the bridge package live, where the candidates are
1. In https://github.com/apollographql/rust
1. in https://github.com/apollographql/apollo-server (under [packages](https://github.com/apollographql/apollo-server/tree/master/packages))
1. a 3rd repository.

There are a few things to take into consideration
1. Maximizing safe development (i.e. compile time stuff)
1. Some Rust toolchain requirements in a TS/JS repository, or vice versa (npm in a rust repository)
1. The release process
1. Enabling reasonable iteration speed / development environment
1. The bridge package is conceptually non-public API
1. The bridge package "ownership": We're all the same team, but really we have people more on the TS side and people more on the Rust side, I suspect it's going to be very natural that where this package ends up going, it's going to be more proverbially "owned" by the people more active in that repository.

As far as I can tell, there's no golden set up for this unless we had a monorepo with everything (which I guess is kind of what https://github.com/apollographql/apollo-platform-devkit does)

## Option 1: The bridge package goes in the rust repository

In this scenario, the bridge package would be a module in the rust repository and part of its monorepo-esque features; we'd compile it along with the packages it uses as dependencies. We'd publish it to npm and depend on it from apollo-server as a dependency like any other. Its semver would reflect API changes, breaking changes, etc. From the perspective of apollo-server, this would be yet another dependency and opaque to the fact that we own all 3 packages.

### On the concerns above:

1. Safety: When working on bridging code, we'd basically writing Rust code that compiles to js/ts. Being in the Rust monorepo means we'll be able to develop on it while developing on other modules in the repository at the same time, or when we make changes in the dependent packages that break the bridge package, we'd get compile time / CI checks verification of that.
1. Toolchain reqs: I'm less familiar with the npm side of things, but we'd need to get whatever tooling we have in the apollo-server repository side to publish to npm under the apollo org into this repository.
1. Release: Again, less familiar, but releasing this package would mean releasing it to npm.
1. Development: Depends on the case, if the developer is more Rust active, and wants to expose something to the JS side, this set up is easier for them. If the developer is more TS active and wants to expose something already public on the Rust side via JS, this set up is harder for them.
1. Exposure: This set up makes what is essentially an internal package public on npm, I'm not sure how common that is and what steps organizations take when this is the case. However, the other side of the coin is that we will not have to expose `apollo-query-planner` in `crates.io`.
1. Owners: In this case, the folks more on the Rust side would be more active owners, I think this may make sense given that the **code** we write (not publish) in this package is dominantly Rust.

## Option 2: The bridge package goes in the apollo-server repository

In this scenario, we add a subdirectory in `packages` in the apollo-server repository which contains pretty much only rust code that we write by hand, except it also contains a `package.json`, but **builds** into a js/ts package. This greatly simplifies our integration story, having this package in this repository will benefit from all of the existing tooling we have to publish versions.

### On the concerns above:

1. Safety: Type checking and safety will happen when someone the TS side attempts to compile against the package they've built locally, which means that if for some reason `apollo-query-planner` made a backwards incompatible change that breaks the API, we'll only discover this after the "bad" code has been merged.
1. Toolchain reqs: the apollo-server repository maintainers will need to install rust and cargo stuff. It's important to note that there are currently a lot more people contributing or trying to contribute to the apollo-server repository.
1. Release: In this set up, releasing means exposing `apollo-query-planner` as a crate to crates.io, then the bridge package consumes it like any other dependency. Eventually we'll need to figure out how to publish to crates.io, this will force us to do this sooner.
1. Development: The opposite case of the above.
1. Exposure: we'd be exposing a "private" library here too, except it's a pure rust one instead of an npm one. So, opposite of the above.
1. Owners: Again, opposite of the above, which I feel may not be as productive, given that I believe Rust developers will more actively work on the code inside this package.

## Option 3: A separate repo all together.

tbh I'm mentioning this because it's an option, but I think it is the worst of all 3 options, with only the advantage of keeping the rust and apollo-server repositories "pure" to their language (ignoring the fact that `cdn` in the rust repo is typescript... so...)

## Summary and personal recommendation

As I was writing this, I convinced myself more and more that the rust repository is the right place for this package. The safety/ownership/development considerations are huge in my opinion, where the downsides (🤷‍♂️) are not any better in the alternative, and are mostly equivalent.

IMO the comparison looks like this: (✅ denoting "better", 🤷‍♂️ denoting not great but not terrible, and 😫 denoting a bummer) 

|	|Rust	|apollo-server	|comments|
|---	|---	|---	|---    |
|safety	|✅	|🤷‍♂️	|Full type safety if this is on the Rust side|
|toolchain reqs	|🤷‍♂️	|😫	|The Rust repo will do npm stuff, but not requiring any rust stuff in apollo-server|
|release	|🤷‍♂️	|🤷‍♂️	|Release to npm, consume from apollo-server vs. release to crates and consume from apollo-server|
|development	|✅	|🤷‍♂️	|I believe Rust developers will dominantly work on this package along side rust code|
|exposure	|🤷‍♂️	|🤷‍♂️	|Exposing the bridge package in npm, vs. exposing the query planner library in crates.io, feels same same to me).|
|owners	|✅	|😫	|Pretty sure we'd want the Rust folks to own this.|

**Comment by abernix** [comment]
@Enrico2 This was really wonderfully laid out; Thanks for putting this together with your thoughts.

#### Option 1 Feedback
> 1. Safety: When working on bridging code, we'd basically writing Rust code that compiles to js/ts. Being in the Rust monorepo means we'll be able to develop on it while developing on other modules in the repository at the same time, or when we make changes in the dependent packages that break the bridge package, we'd get compile time / CI checks verification of that.

Agree!  There is still a chance that whatever changes get published will break when Apollo Server tries to use the new package though.  Apollo Server will automatically (albeit with an ~hour delay) receive updates to this package via Renovate Bot when new copies of the WASM npm package are published.  The testsuite will run automatically on that PR, and then we'd find out things failed.

(Getting off topic from my thoughts on _safety_ here: We can head this failure off a lot sooner by using GitHub Actions to run each commit on `rust` through a smoke-test with Apollo Server.  The Action could `wasm-pack` the package on the `rust` repo to get an `npm install`-able `.tar.gz`, then clone the Apollo Server default branch (e.g., directly from `git@github:apollographql/apollo-server.git`) and `npm install the-tarball.tar.gz` into it and run it's `npm test` script.)

> 2. Toolchain reqs: I'm less familiar with the npm side of things, but we'd need to get whatever tooling we have in the apollo-server repository side to publish to npm under the apollo org into this repository.

> 3. Release: Again, less familiar, but releasing this package would mean releasing it to npm.

Both of these would be pretty simple, particularly without Lerna.  I think one good option would just use a GitHub Action to publish them directly to npm as `@apollo/query-planner-wasm`.  (Here I am talking about GitHub Actions again, but I think they're going to help us a lot.)

> 4. Development: Depends on the case, if the developer is more Rust active, and wants to expose something to the JS side, this set up is easier for them. If the developer is more TS active and wants to expose something already public on the Rust side via JS, this set up is harder for them.

I suspect we're going to want to be more _Rust-active_ in general on this work, so I think this is a strong argument for this option.

> 5. Exposure: This set up makes what is essentially an internal package public on npm, I'm not sure how common that is and what steps organizations take when this is the case. However, the other side of the coin is that we will not have to expose `apollo-query-planner` in `crates.io`.

I think having the package on npm is great, even if it seems internal.  We do that already (today) with a number of packages (mostly utilities).   That said, I'm also not convinced it's necessary to deem the npm package as internal though.  I think this package could be readily consumed by whoever wanted to plan queries, no?

> 6. Owners: In this case, the folks more on the Rust side would be more active owners, I think this may make sense given that the **code** we write (not publish) in this package is dominantly Rust.

Agree.

#### Option 2 Feedback

> 1. Safety: Type checking and safety will happen when someone the TS side attempts to compile against the package they've built locally, which means that if for some reason `apollo-query-planner` made a backwards incompatible change that breaks the API, we'll only discover this after the "bad" code has been merged.

There are still the risks of type changes on the `rust` side resulting compilation problems when the new npm is (eventually) installed in `@apollo/gateway`.  However, I think we can avoid those chances using the solution I offered in the `1.` bullet-point above about smoke-testing Apollo Server.  This smoke-testing has an added benefit of helping us semantically version the local package appropriately by testing it with its most popular consumer.  (We could even invite _other_ populate gateway projects to contribute their own test suite that runs against our commits here in `rust`?)

> 2. Toolchain reqs: the apollo-server repository maintainers will need to install rust and cargo stuff. It's important to note that there are currently a lot more people contributing or trying to contribute to the apollo-server repository.

Yeah, I think avoiding Rust in AS-land is nice.  As it is right now we have some special compilation steps which have caused roadblocks for some users (i.e. the `apollo-engine-reporting-protobuf` stuff).  While I do think we _could_ wire it up to not interfere with those who didn't need to be concerned with it, I'd rather we avoid that wiring-up.

> 3. Release: In this set up, releasing means exposing `apollo-query-planner` as a crate to crates.io, then the bridge package consumes it like any other dependency. Eventually we'll need to figure out how to publish to crates.io, this will force us to do this sooner.

Let's publish a 📦! (I mean, a _crate_.  Let's not publish a cardboard box.)

> 4. Development: The opposite case of the above.

We have a lot of Rust work to do.  I would rather not concern incoming Rust contributors with the unfamiliar terrain of Apollo Server Core.  (Put concretely: Yup, I still think _Option 1_ is better.)

> 5. Exposure: we'd be exposing a "private" library here too, except it's a pure rust one instead of an npm one. So, opposite of the above.

I think both are okay.  I do think we'll want to have query planners which can be called from other Node.js and Rust projects alike.

> 6. Owners: Again, opposite of the above, which I feel may not be as productive, given that I believe Rust developers will more actively work on the code inside this package.

Yep.  Less productive.

---

I completely convinced that we should _not_ introduce Rust tooling to the Apollo Server repo and in favor of _Option 1_.

One note though:

> So far we've agreed on the following set up:
> 
> 1. A pure Rust package containing the Rust objects, business logic, etc.
> 2. A wasm bridge rust+js, this one depends on the pure Rust packages and exposes js/ts (not sure yet) to be used by the gateway.
> 3. The gateway ts code will have a dependency on the bridge package and will use whatever it exposes.

I'm realizing after reading this that there is a subtle bit of nuance that I think might be worth clarifying after looking at the two options.

With _Option 2_ there is actually another **necessary** (Rust) component in play that lives within the Apollo Server repository, right?  Like, a package that re-exports `query-planner` but with bindgen annotations?  (Thinking about this more I feel pretty unsafe with this option generally, if so.)

_Another_ advantage of _Option 1_ would seem to be that _component 1_ and _component 2_ (in the bullet-points quoted just above) are just the **same package**: The "bridge" is just emitted from the single Rust query planner crate's build process (i.e. `wasm-pack`) and published to npm.

Anyhow, I'm convinced _Option 1_ is the way to go.  I'd claim we just need one `query-planner` with bindgen annotations throughout that emits a package that we publish to npm from the `rust` repo (with GitHub Actions).

What do you think about the smoke-testing suggestion I offered above?  I think it's just a few lines of GitHub Actions code:

<details>
<summary><u>_Click to see what I'm suggesting as a GitHub Action_</u></summary>

```yaml
name: Smoke Test Apollo Gateway
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Clone Apollo Server
      run: |
        # Build the npm module for local testing, don't publish.
        (cd query-planner && wasm-pack build --target nodejs)
        # Clone Apollo Server's repo.
        git clone https://github.com/apollographql/apollo-server apollo-server
        cd apollo-server/
        npm ci-install
        # Override with local pkg we built above.
        npm install ../query-planner/pkg/
        # Test the gateway with it! (presumably it uses this pkg).
        npm t -- packages/apollo-gateway/
```

</details>

**Comment by Enrico2** [comment]
Thanks @abernix ! Sounds like we're on the same page.

@ashleygwilliams also suggested we annotate in the packages directly, but I've yet to learn what are the consequences of that. 

Will we be packing a lot of code expanded from macros that will only be used by the bridge package? Are we coupling together these concerns instead of having a clear line between each crate's role in the stack?

When we make the Rust gateway implementation do more and more, e.g. maybe it'll implement a full request-response flow, and then the query planning is completely contained to Rust, maybe in that scenario we'd need less bridging, but still want to be able to build both options? 

From an architecture perspective, decoupling the crates and not assuming something will be used in a specific way makes sense to me, but if there are still some limitations to work around, or the ergonomics of coupling are worth it, then let's move forward. 

I suspect Ashley can help a lot here, so we'll discuss more next week :)

**Comment by Enrico2** [comment]
We've landed on putting the bridge package in the Rust repo, unless it proves to be problematic down the line.
