### ISSUE TITLE
checkin Cargo.lock

### ISSUE THREAD

**Issue by ashleygwilliams** [apollographql/rust#78]

**Comment by Enrico2** [comment]
I was reading this: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

And then I wasn't 100% sure what would be the best strategy there with a monorepo  type situation where we have both libraries and a binary, but a single `Cargo.lock`

(that is to say, if checking it in is the right thing, that's totally fine w/ me :))

**Comment by ashleygwilliams** [comment]
i would generally say checking it in is the right thing to do. when installing a rust library, cargo will always ignore the Cargo.lock, whereas folks working on the tool can use the Cargo.lock to ensure conformity across dev envs.
