### ISSUE TITLE
remove TODO from codebase

### ISSUE THREAD

**Issue by ashleygwilliams** [apollographql/rust#89]
there are several TODO comments in the repo (https://github.com/apollographql/rust/search?q=TODO&unscoped_q=TODO).

i am of the opinion that we should file as issues for better discoverability, so i am going ahead and doing that. longterm i'd like to avoid using TODO comments when at all necessary. what are people's thoughts?

**Comment by Enrico2** [comment]
In our other monorepo we had 2 variations:

1. `TODO`s along with a reference to a ticket/issue - these are allowed to be checked in. I personally find these to be invaluable in a code base. Having context _in the code_ directly that a certain area has some kind of flag next to it, without having to remember all the open issues by heart is critical IMO to not stop someone's flow. It's also very common to encounter something that you feel should be changed but is too large of a distraction to do from the current task at hand. Putting a TODO with a pointer to an issue is leaving a road sign for future code readers that "there be monsters".
2. `FIXME`s - These are a convenience to a developer to say "this is work in progress, a reminder to myself to come back here before merging". **Any instance of that string caused CI to fail**. You'd see these in large-ish PRs that build out incrementally (e.g. `// FIXME - write a unit test for this!`)

So, thanks for annotating the existing `TODO`s with issues! 

I don't think avoiding them all together would create more value than they offer, you did say "when at all necessary", so maybe what I'm considering the "good" way to use a TODO is what you deem necessary?

(I like it when `TODO`s mention the author too)

**Comment by designatednerd** [comment]
FWIW I've always found TODO annotated with related ticket to be helpful as long as you actually go through them once in a while and fix them 😆
