### ISSUE TITLE
Any plans regarding a pure Rust federation gateway?

### ISSUE THREAD

**Issue by teh-cmc** [apollographql/rust#98]
Hey folks; I've stumbled upon this repository and it looks like it has already grown far beyond its original scope of offering a new CLI, which piqued my interest :upside_down_face: 

I'd be very interested in being able to run a pure Rust gateway for federated services, is there any intent of pushing this effort towards that? Or maybe is that the kind of community contribution you'd be interested in?

**Comment by jbaxleyiii** [comment]
Hello @teh-cmc!

The short answer is very much yes! We have already started porting of the query planning fuctionality from the TypeScript codebase to this one so we can begin to build out a Rust gateway. 

I'd love to learn more about why you are interested in a Rust gateway if you would be up for sharing!

**Comment by Enrico2** [comment]
We are planning on starting this work in the immediate future so I'm going to close this issue but feel free to open another or reach out if you have questions!

**Comment by teh-cmc** [comment]
Apologies for not responding earlier, I got caught on a gazillion other things, as one does...

I'm very glad to hear that! To quickly answer your question: on one hand our internal GraphQL infrastructure has been steadily growing over the last year, to the point where we really start to feel the need to decouple our various nodes both in terms of code and of ownership, and on the other hand our expertise in-house is mostly centered around systems programming & natively compiled languages (mostly C++, Go and Rust these days), so having to operate a JS runtime and the ginormous ecosystem that comes with it right in the middle of our stack is kind of a pain for us... :)

Anyway, I'll be following this one closely; thanks for all the great work! Cheers.
